Accept=Onartu
Close=Atzera joan
Price= Prezioa
SelectOption=Aukeratu

MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.Login= Saioa hasi
MainGUI.Register= Erregistratu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua
MainGUI.ChangeToSeller=Saltzaile modura aldatu
MainGUI.ChangeToBuyer=Erosle modura aldatu
MainGUI.Seller=Saltzaile moduan
MainGUI.Buyer=Erosle moduan

MainGUIBuyer.ShowPurchased=Ikusi erositakoak
MainGUIBuyer.ManageBalance=Saldoa kudeatu

BalanceManagerGUI.Withdraw=Dirua atera
BalanceManagerGUI.Insert=Saldoa gehitu
BalanceManagerGUI.Close=Atzera joan
BalanceManagerGUI.ShowTransactions=Transakzioak ikusi

WithdrawMoneyGUI.Withdraw=Dirua atera
WithdrawMoneyGUI.Close=Atzera joan
WithdrawMoneyGUI.CreditCard=Txartelaren zenbakia idatzi:
WithdrawMoneyGUI.Amount=Zenbat atera nahi duzu?
WithdrawMoneyGUI.EmptyError=Error, datuak falta dira
WithdrawMoneyGUI.NumberError=Error, txartel zenbakia 16 digitukoa izan behar du
WithdrawMoneyGUI.FormatError=Error, kopurua zenbaki bat izan behar du
WithdrawMoneyGUI.AllGood=Zure saldo berria:
WithdrawMoneyGUI.BalanceError=Ez dago saldo nahikoa, momentuko saldoa:

InsertMoneyGUI.Insert=Saldoa gehitu
InsertMoneyGUI.Close=Atzera joan
InsertMoneyGUI.CreditCard=Txartelaren zenbakia idatzi:
InsertMoneyGUI.Amount=Zenbat gehitu nahi duzu?
InsertMoneyGUI.EmptyError=Error, datuak falta dira
InsertMoneyGUI.NumberError=Error, txartel zenbakia 16 digitukoa izan behar du
InsertMoneyGUI.FormatError=Error, biek zenbaki bat izan behar dute
InsertMoneyGUI.AllGood=Zure saldo berria:

CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=Error, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak
ShowSaleGUI.Buy=Erosi
ShowSaleGUI.MenuReport=Salatu
ShowSaleGUI.BalanceError=Ez dago saldo nahikoa, momentuko saldoa:

ShowPurchasedListGUI.Title=Erositakoak
ShowPurchasedListGUI.Purchased=Zure erosketak
ShowPurchasedListGUI.Show=Ikusi
ShowPurchasedListGUI.Press=Sakatu "ikusi" erosketak ikusteko

LoginGUI.UserName=Erabiltzailea
LoginGUI.Password=Pasahitza
LoginGUI.Login=Hasi saioa
LoginGUI.ErrorEmpty=Error, datuak falta dira
LoginGUI.NotExist=Error, erabiltzailea ez da existitzen
LoginGUI.LblRegister=Ez duzu konturik? Sortu bat hemen
LoginGUI.Register=Erregistratu
LoginGUI.Back=Atzera joan

RegisterGUI.NewUser=Erabiltzailea berria
RegisterGUI.Email=Korreo berria
RegisterGUI.Password1=Pasahitza
RegisterGUI.Password2=Errepikatu Pasahitza
RegisterGUI.Warning=Kontua jada existitzen da
RegisterGUI.ErrorEmpty=Error, datuak falta dira
RegisterGUI.ErrorPass=Error, pasahitzek bat etorri behar dute
RegisterGUI.Register=Erregistratu
RegisterGUI.Exist=Error, dagoeneko existitzen da
RegisterGUI.AlreadyRegistered=Baduzu  konturik? Hasi saioa hemen
RegisterGUI.Login=Hasi saioa
RegisterGUI.Back=Atzera joan

ReportGUI.Close=Atzera joan
ReportGUI.Header=Idatzi burukoa:
ReportGUI.Reason=Idatzi arrazoia:
ReportGUI.AllGood=Arrakastaz salatuta
ReportGUI.EmptyError=Error, datuak falta dira
ReportGUI.Report=Salatu

DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da